language: julia
julia:
  - 1.0
  - 1.1
  - 1.3
  - 1.4
  - nightly
matrix:
  allow_failures:
    - julia: nightly
os:
  - linux
  - osx
notifications:
  email: false
after_success:
    - julia -e 'using Pkg; pkg"add Coverage"; using Coverage; Codecov.submit(Codecov.process_folder())'

jobs:
  include:
    - stage: "Documentation"
      julia: 1.3
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                               Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip
